version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
